/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as governorSol from "./Governor.sol";
export { GovernanceToken__factory } from "./GovernanceToken__factory";
export { GovernanceTokenWrapped__factory } from "./GovernanceTokenWrapped__factory";
export { Target__factory } from "./Target__factory";
export { TimeLock__factory } from "./TimeLock__factory";
