/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as governorSol from "./Governor.sol";
export type { governorSol };
export type { GovernanceToken } from "./GovernanceToken";
export type { GovernanceTokenWrapped } from "./GovernanceTokenWrapped";
export type { Target } from "./Target";
export type { TimeLock } from "./TimeLock";
